-- Seed data for tbl_countries table
-- Common countries for a German tutoring platform

-- Insert countries with their ISO codes and full names
INSERT INTO tbl_countries (fld_id, fld_landx, fld_landx50, fld_lflag) VALUES
(1, 'DE', 'Deutschland', 'Active'),
(2, 'AT', 'Österreich', 'Active'),
(3, 'CH', 'Schweiz', 'Active'),
(4, 'US', 'Vereinigte Staaten', 'Active'),
(5, 'GB', 'Vereinigtes Königreich', 'Active'),
(6, 'FR', 'Frankreich', 'Active'),
(7, 'IT', 'Italien', 'Active'),
(8, 'ES', 'Spanien', 'Active'),
(9, 'NL', 'Niederlande', 'Active'),
(10, 'BE', 'Belgien', 'Active'),
(11, 'DK', 'Dänemark', 'Active'),
(12, 'SE', 'Schweden', 'Active'),
(13, 'NO', 'Norwegen', 'Active'),
(14, 'FI', 'Finnland', 'Active'),
(15, 'PL', 'Polen', 'Active'),
(16, 'CZ', 'Tschechien', 'Active'),
(17, 'HU', 'Ungarn', 'Active'),
(18, 'SK', 'Slowakei', 'Active'),
(19, 'SI', 'Slowenien', 'Active'),
(20, 'HR', 'Kroatien', 'Active'),
(21, 'RO', 'Rumänien', 'Active'),
(22, 'BG', 'Bulgarien', 'Active'),
(23, 'GR', 'Griechenland', 'Active'),
(24, 'PT', 'Portugal', 'Active'),
(25, 'IE', 'Irland', 'Active'),
(26, 'LU', 'Luxemburg', 'Active'),
(27, 'MT', 'Malta', 'Active'),
(28, 'CY', 'Zypern', 'Active'),
(29, 'EE', 'Estland', 'Active'),
(30, 'LV', 'Lettland', 'Active'),
(31, 'LT', 'Litauen', 'Active'),
(32, 'CA', 'Kanada', 'Active'),
(33, 'AU', 'Australien', 'Active'),
(34, 'NZ', 'Neuseeland', 'Active'),
(35, 'JP', 'Japan', 'Active'),
(36, 'KR', 'Südkorea', 'Active'),
(37, 'CN', 'China', 'Active'),
(38, 'IN', 'Indien', 'Active'),
(39, 'BR', 'Brasilien', 'Active'),
(40, 'AR', 'Argentinien', 'Active'),
(41, 'MX', 'Mexiko', 'Active'),
(42, 'RU', 'Russland', 'Active'),
(43, 'UA', 'Ukraine', 'Active'),
(44, 'BY', 'Belarus', 'Active'),
(45, 'TR', 'Türkei', 'Active'),
(46, 'EG', 'Ägypten', 'Active'),
(47, 'ZA', 'Südafrika', 'Active'),
(48, 'NG', 'Nigeria', 'Active'),
(49, 'KE', 'Kenia', 'Active'),
(50, 'MA', 'Marokko', 'Active'),
(51, 'TN', 'Tunesien', 'Active'),
(52, 'DZ', 'Algerien', 'Active'),
(53, 'LY', 'Libyen', 'Active'),
(54, 'SD', 'Sudan', 'Active'),
(55, 'ET', 'Äthiopien', 'Active'),
(56, 'GH', 'Ghana', 'Active'),
(57, 'CI', 'Elfenbeinküste', 'Active'),
(58, 'SN', 'Senegal', 'Active'),
(59, 'ML', 'Mali', 'Active'),
(60, 'BF', 'Burkina Faso', 'Active'),
(61, 'NE', 'Niger', 'Active'),
(62, 'TD', 'Tschad', 'Active'),
(63, 'CM', 'Kamerun', 'Active'),
(64, 'CF', 'Zentralafrikanische Republik', 'Active'),
(65, 'CG', 'Kongo', 'Active'),
(66, 'CD', 'Demokratische Republik Kongo', 'Active'),
(67, 'AO', 'Angola', 'Active'),
(68, 'ZM', 'Sambia', 'Active'),
(69, 'ZW', 'Simbabwe', 'Active'),
(70, 'BW', 'Botswana', 'Active'),
(71, 'NA', 'Namibia', 'Active'),
(72, 'SZ', 'Eswatini', 'Active'),
(73, 'LS', 'Lesotho', 'Active'),
(74, 'MG', 'Madagaskar', 'Active'),
(75, 'MU', 'Mauritius', 'Active'),
(76, 'SC', 'Seychellen', 'Active'),
(77, 'KM', 'Komoren', 'Active'),
(78, 'DJ', 'Dschibuti', 'Active'),
(79, 'SO', 'Somalia', 'Active'),
(80, 'ER', 'Eritrea', 'Active'),
(81, 'UG', 'Uganda', 'Active'),
(82, 'TZ', 'Tansania', 'Active'),
(83, 'RW', 'Ruanda', 'Active'),
(84, 'BI', 'Burundi', 'Active'),
(85, 'MW', 'Malawi', 'Active'),
(86, 'MZ', 'Mosambik', 'Active'),
(87, 'TH', 'Thailand', 'Active'),
(88, 'VN', 'Vietnam', 'Active'),
(89, 'PH', 'Philippinen', 'Active'),
(90, 'ID', 'Indonesien', 'Active'),
(91, 'MY', 'Malaysia', 'Active'),
(92, 'SG', 'Singapur', 'Active'),
(93, 'HK', 'Hongkong', 'Active'),
(94, 'TW', 'Taiwan', 'Active'),
(95, 'MM', 'Myanmar', 'Active'),
(96, 'LA', 'Laos', 'Active'),
(97, 'KH', 'Kambodscha', 'Active'),
(98, 'BD', 'Bangladesch', 'Active'),
(99, 'LK', 'Sri Lanka', 'Active'),
(100, 'MV', 'Malediven', 'Active')
ON CONFLICT (fld_id) DO NOTHING;

-- Update the sequence to start from the correct value
SELECT setval('tbl_countries_fld_id_seq', 100, true);
